<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category' => 'bears',
                'name' => 'Плюшевый медведь Бублик',
                'slug' => 'bear-bublik',
                'description' => 'Большой добрый мишка из мягкого плюша с пушистой шёрсткой. Сидит устойчиво, обнимает крепко, а его лапы идеально подходят для того, чтобы держать за руку перед сном.',
                'price' => 2490,
                'old_price' => 2990,
                'image' => '/images/products/bear-bublik.svg',
                'size' => '35 см',
                'material' => 'Плюш, холлофайбер',
                'stock' => 18,
                'is_featured' => true,
            ],
            [
                'category' => 'bears',
                'name' => 'Плюшевый медведь Мятный',
                'slug' => 'bear-mint',
                'description' => 'Мишка нежного мятного оттенка с бантом из атласной ленты. Любимец малышей: небольшой размер удобно держать в коляске и брать в поездки.',
                'price' => 2190,
                'image' => '/images/products/bear-mint.svg',
                'size' => '28 см',
                'material' => 'Плюш, синтепух',
                'stock' => 12,
                'is_featured' => false,
            ],
            [
                'category' => 'cats',
                'name' => 'Плюшевый кот Мурчик',
                'slug' => 'cat-murchik',
                'description' => 'Серый полосатый котик с розовым носиком и мягкими лапками. Умеет «мурчать» — достаточно погладить бочок, и настроение становится лучше.',
                'price' => 1890,
                'old_price' => 2290,
                'image' => '/images/products/cat-murchik.svg',
                'size' => '25 см',
                'material' => 'Плюш, холлофайбер',
                'stock' => 24,
                'is_featured' => true,
            ],
            [
                'category' => 'cats',
                'name' => 'Плюшевая кошка Лапушка',
                'slug' => 'cat-lapushka',
                'description' => 'Пушистая белая кошечка с голубым бантом и длинным хвостом. Отличный подарок для тех, кто любит уютные мелочи.',
                'price' => 2050,
                'image' => '/images/products/cat-lapushka.svg',
                'size' => '27 см',
                'material' => 'Искусственный мех, холлофайбер',
                'stock' => 15,
                'is_featured' => false,
            ],
            [
                'category' => 'capybaras',
                'name' => 'Плюшевая капибара Капи',
                'slug' => 'capybara-kapi',
                'description' => 'Самая спокойная капибара на свете. Тяжёленькая, с приятной плотной набивкой — её так и хочется посадить рядом на диван и обнять.',
                'price' => 2690,
                'image' => '/images/products/capybara-kapi.svg',
                'size' => '30 см',
                'material' => 'Плюш, гранулят, холлофайбер',
                'stock' => 20,
                'is_featured' => true,
            ],
            [
                'category' => 'bunnies',
                'name' => 'Плюшевый зайчик Пух',
                'slug' => 'bunny-puh',
                'description' => 'Зайчик с длинными ушками и мягким животиком. Ушки можно завязать бантом — малыши обожают эту игрушку.',
                'price' => 1790,
                'image' => '/images/products/bunny-puh.svg',
                'size' => '24 см',
                'material' => 'Велюр, холлофайбер',
                'stock' => 30,
                'is_featured' => true,
            ],
            [
                'category' => 'foxes',
                'name' => 'Плюшевая лиса Рыжик',
                'slug' => 'fox-ryzhik',
                'description' => 'Хитрая, но очень добрая лиса с белым кончиком хвоста. Отлично сидит, хвост можно обнимать как маленькую подушку.',
                'price' => 2350,
                'image' => '/images/products/fox-ryzhik.svg',
                'size' => '32 см',
                'material' => 'Плюш, холлофайбер',
                'stock' => 16,
                'is_featured' => true,
            ],
            [
                'category' => 'dinosaurs',
                'name' => 'Плюшевый динозавр Дино',
                'slug' => 'dino-dino',
                'description' => 'Зелёный динозаврик с гребнем и мягкими шипами. Совсем не страшный — наоборот, охраняет сон.',
                'price' => 2490,
                'image' => '/images/products/dino-dino.svg',
                'size' => '34 см',
                'material' => 'Плюш, велсофт, холлофайбер',
                'stock' => 14,
                'is_featured' => true,
            ],
            [
                'category' => 'axolotls',
                'name' => 'Плюшевый аксолотль Аксель',
                'slug' => 'axolotl-aksel',
                'description' => 'Розовый аксолотль с жабрышками и улыбкой до ушей. Самый фотогеничный житель Softy.',
                'price' => 2290,
                'image' => '/images/products/axolotl-aksel.svg',
                'size' => '30 см',
                'material' => 'Плюш, холлофайбер',
                'stock' => 22,
                'is_featured' => true,
            ],
            [
                'category' => 'pillows',
                'name' => 'Большая игрушка-подушка Облачко',
                'slug' => 'pillow-cloud',
                'description' => 'Огромное плюшевое облако-подушка 60 см. Идеально для чтения, кино и сна в обнимку. Наполнитель держит форму и не сбивается в комки.',
                'price' => 4590,
                'old_price' => 5290,
                'image' => '/images/products/pillow-cloud.svg',
                'size' => '60 см',
                'material' => 'Плюш, силиконизированное волокно',
                'stock' => 8,
                'is_featured' => true,
            ],
            [
                'category' => 'pillows',
                'name' => 'Игрушка-подушка Кот-батон',
                'slug' => 'pillow-cat-baton',
                'description' => 'Тот самый кот-батон: длинный, мягкий и очень удобный в качестве подушки под шею. Чехол снимается и стирается.',
                'price' => 3990,
                'image' => '/images/products/pillow-cat-baton.svg',
                'size' => '50 см',
                'material' => 'Плюш, силиконизированное волокно',
                'stock' => 10,
                'is_featured' => false,
            ],
            [
                'category' => 'minis',
                'name' => 'Мини-игрушка Медвежонок Тишка',
                'slug' => 'mini-bear-tishka',
                'description' => 'Карманный медвежонок 15 см. Приятно положить в рюкзак или подарить коллеге — маленький, а радости много.',
                'price' => 990,
                'image' => '/images/products/mini-bear-tishka.svg',
                'size' => '15 см',
                'material' => 'Плюш, холлофайбер',
                'stock' => 46,
                'is_featured' => false,
            ],
            [
                'category' => 'minis',
                'name' => 'Мини-игрушка Капибара Пип',
                'slug' => 'mini-capybara-pip',
                'description' => 'Мини-капибара, которая помещается в ладошку. Отличный талисман и подарок-комплимент.',
                'price' => 1090,
                'image' => '/images/products/mini-capybara-pip.svg',
                'size' => '16 см',
                'material' => 'Плюш, холлофайбер',
                'stock' => 40,
                'is_featured' => false,
            ],
            [
                'category' => 'bears',
                'name' => 'Плюшевый ленивец Соня',
                'slug' => 'sloth-sonya',
                'description' => 'Ленивец, который всегда готов поспать вместе с вами. Длинные лапки удобно свешиваются с полки.',
                'price' => 2590,
                'image' => '/images/products/sloth-sonya.svg',
                'size' => '33 см',
                'material' => 'Велюр, холлофайбер',
                'stock' => 11,
                'is_featured' => false,
            ],
            [
                'category' => 'minis',
                'name' => 'Мягкая черепашка Тимка',
                'slug' => 'turtle-timka',
                'description' => 'Черепашка с рельефным панцирем из фактурной ткани. Приятно перебирать пальцами — настоящий антистресс.',
                'price' => 1690,
                'image' => '/images/products/turtle-timka.svg',
                'size' => '22 см',
                'material' => 'Фактурный плюш, холлофайбер',
                'stock' => 19,
                'is_featured' => false,
            ],
        ];

        $categories = Category::pluck('id', 'slug');

        foreach ($products as $product) {
            Product::create([
                'category_id' => $categories[$product['category']],
                'name' => $product['name'],
                'slug' => $product['slug'],
                'description' => $product['description'],
                'price' => $product['price'],
                'old_price' => $product['old_price'] ?? null,
                'image' => $product['image'],
                'size' => $product['size'],
                'material' => $product['material'],
                'stock' => $product['stock'],
                'is_featured' => $product['is_featured'],
            ]);
        }
    }
}
